# Generated by Django 6.0.3 on 2026-07-08 15:11

from django.db import migrations, models

import tests.app.models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDisplayGarment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("size", models.CharField(choices=tests.app.models.size_choices, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Garment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("size", models.CharField(choices=tests.app.models.size_choices, max_length=1)),
            ],
        ),
    ]
