# Generated by Django 3.0.8 on 2020-08-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="occupation", name="boolean", field=models.BooleanField(null=True)
        ),
        migrations.AlterField(
            model_name="occupation",
            name="boolean_with_choices",
            field=models.BooleanField(choices=[(True, "Yes"), (False, "No")], null=True),
        ),
    ]
