# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-30 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.PositiveIntegerField(verbose_name='population'),
        ),
    ]
